spring:
  application:
    name: torg-codex
    version: "@project.version@"
    # noinspection SpringBootApplicationYaml
    description: "@project.description@"

  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 4
      validation-timeout: 30000
      connection-test-query: "SELECT 1"
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  jackson:
    datatype:
      enum:
        write-enums-using-to-string: true
        read-enums-using-to-string: true

gg:
  jte:
    development-mode: true

logging:
  level:
    root: info
    de.paladinsinn: debug
    de.paladinsinn.torg.codex: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  tracing:
    enabled: false
    export:
      otlp:
        enabled: false
  endpoint:
    health:
      group:
        liveness:
          include:
          - livenessState
          show-details: always
        readiness:
          include:
          - readinessState
          - db
          - mail
          show-details: always
      probes:
        enabled: true
      show-details: always
      validate-group-membership: false
      cache:
        time-to-live: 5s
    info:
      cache:
        time-to-live: 5s
    metrics:
      cache:
        time-to-live: 5s
    loggers:
      access: read_only
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
          - loggers
          - logfile
          - liquidbase
          - hikari
          - quartz
